# Generated by Django 5.1.3 on 2024-11-22 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2024, 11, 22, 13, 7, 1, 775704), verbose_name='Дата создания')),
                ('post_content', models.TextField(verbose_name='Содержание статьи')),
            ],
        ),
    ]
