# Generated by Django 5.1.3 on 2024-11-22 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_creator',
            field=models.CharField(default='guest', max_length=100, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 17, 19, 49, 765849), verbose_name='Дата создания'),
        ),
    ]
